### ISSUE TITLE
Can't add card with 0.0.2

### ISSUE THREAD

**Issue by margatemarcel** [lnbits/boltcards#14]
First time user trying to add first NFC card to boltcards extension v0.0.2.

Kept getting following error:

<img width="823" alt="boltcard_error" src="https://github.com/lnbits/boltcards/assets/37417851/895aeae1-97b2-4964-ba24-a54ca119efdd">

Worked fine on legend (0.0.1 extension) and someone else's instance (also 0.0.1).

Finally figured out how to manually downgrade extension (by copying files manually) to 0.0.1 on my own instance and I can now add the UID.

So I can only assume that 0.0.2 has broken things.

**Comment by talvasconcelos** [comment]
Can't reproduce your error, just added a new card, on 0.0.2/main! 

Can you describe the steps? 
What browser are you using?

We fixed the validation error on 0.0.2

**Comment by massmux** [comment]
same error here with 0.0.2

**Comment by margatemarcel** [comment]
> pls provide the link of the previous working version that you tested. in order to install manually

https://github.com/lnbits/boltcards/releases/tag/0.0.0.1

**Comment by massmux** [comment]
> > pls provide the link of the previous working version that you tested. in order to install manually
> 
> https://github.com/lnbits/boltcards/releases/tag/0.0.0.1



> First time user trying to add first NFC card to boltcards extension v0.0.2.
> 
> Kept getting following error:
> <img alt="boltcard_error" width="823" src="https://user-images.githubusercontent.com/37417851/261799031-895aeae1-97b2-4964-ba24-a54ca119efdd.png">
> 
> Worked fine on legend (0.0.1 extension) and someone else's instance (also 0.0.1).
> 
> Finally figured out how to manually downgrade extension (by copying files manually) to 0.0.1 on my own instance and I can now add the UID.
> 
> So I can only assume that 0.0.2 has broken things.

to downgrade, did you uninstalled the previous one from the dashboard and then installed from the tar file?

**Comment by margatemarcel** [comment]
No, I manually replaced `~/lnbits/data/extensions/boltcards.zip` and removed/replaced the files in `~/lnbits/lnbits/extensions/boltcards` from the updated .zip file.

I couldn't find a cleaner way to get it working at this time (it still appears as 0.0.2, but works).

**Comment by dni** [comment]
we merged this:  https://github.com/lnbits/boltcards/pull/15

and after we merge this i will release 0.0.3

it should be resolved with that

**Comment by dni** [comment]
boltcards 0.0.3 released it should fix this issue, can you try?

**Comment by saerdnaa** [comment]
Yes, it works fine for me. Thanks

**Comment by dni** [comment]
brilliant

**Comment by massmux** [comment]
> boltcards 0.0.3 released it should fix this issue, can you try?

Great work! thanks!

**Comment by margatemarcel** [comment]
Confirmed working for me too - many thanks.
